name: Release Beta

on:
  push:
    tags:
      - "v*.*.*-beta.*"

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Make and publish (prerelease)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORGE_PUBLISH_DRAFT: "false"
          FORGE_PUBLISH_PRERELEASE: "true"
        run: npm run publish
